// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {

  url = 'https://www.amiiboapi.com/api/amiibo'

  amiibos

  constructor(private http: HttpClient) { }

  ngOnInit() {
    this.amiibos = this.http.get(this.url).pipe(map(({ amiibo }: any) => amiibo))

  }
}

<main>
  <h1 class="title">Amiibos</h1>
  <ul class="list">
    <li *ngFor="let amiibo of (amiibos | async)" class="item">
      <img [src]="amiibo.image" [alt]="amiibo.name" [title]="amiibo.name" />
      <div class="item-description">
        <h2 class="item-name">{{ amiibo.name }}</h2>
        <p>Game Serie: {{ amiibo.amiiboSeries }}</p>
        <p>Release: {{amiibo.release.eu || amiibo.release.jp || amiibo.release.na || amiibo.release.au}}</p>
      </div>
    </li>
  </ul>
</main>

// react/src/App.js
import React, { useState, useEffect } from 'react'
import './style.css'

const url = 'https://www.amiiboapi.com/api/amiibo'

function App() {
  const [amiibos, setAmiibos] = useState([])

  useEffect(() => {
    fetch(url).then(result => result.json()).then(({ amiibo }) => setAmiibos(amiibo))
  }, [])

  return (
    <main>
      <h1 class="title">Amiibos</h1>
      <ul class="list">
        {amiibos.map(({ name, image, amiiboSeries, release }) => (
          <li key={name} className="item">
            <img src={image} alt={name} title={name} />
            <div class="item-description">
              <h2 class="item-name">{name}</h2>
              <p>Game Serie: {amiiboSeries}</p>
              <p>Release: {release.eu ?? release.jp ?? release.na ?? release.au}</p>
            </div>
          </li>
        ))}
      </ul>
    </main>
  );
}

export default App
